#!/bin/bash

## Get data
STATUS="$(audtool playback-status)"
COVER="/tmp/.music_cover.jpg"
# MUSIC_DIR="/media/antihero/Data/Songs/"

## Get status
get_status() {
	if [[ $STATUS == "playing" ]]; then
		echo ""
	else
		echo "喇"
	fi
}

## Get song
get_song() {
	song=$(audtool --current-song-tuple-data title)
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=$(audtool --current-song-tuple-data artist)
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	start_i=$(audtool current-song-output-length-seconds)
	end_i=$(audtool current-song-length-seconds)
	time=$((start_i * 100 / end_i))
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=$(audtool current-song-output-length)
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=$(audtool current-song-length)
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Get cover
get_cover() {
	SONG_NAME="$(audtool current-song-filename | sed 's.//./.')"
	ffmpeg -i "$SONG_NAME" "${COVER}" -y &> /dev/null
	STATUS=$?

	# Check if the file has a embbeded album art
	if [ "$STATUS" -eq 0 ];then
		echo "$COVER"
	else
		echo "images/music.png"
	fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	audacious -t
elif [[ "$1" == "--next" ]]; then
	{ audacious -f; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ audacious -r; get_cover; }
fi
