#!/bin/bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/Software/source/eww/target/release/eww"

if [[ "$1" == "--dl" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/Documents &

elif [[ "$1" == "--music" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/Music &

elif [[ "$1" == "--pics" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/.config &

elif [[ "$1" == "--local" ]]; then
	${EWW} close-all && rm -rf "$FILE" && dolphin ~/.local/share &

fi
