#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/Software/source/eww/target/release/eww"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   github \
		   reddit \
		   twitter \
		   youtube \
		   apps \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders \
		   mic \
		   quotes
}


## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all
	rm "$FILE"
fi
