#!/bin/bash

filter='
@a = <>; 
$a=join("", @a); 
$a =~ s/\n(\S)/\n\n$1/g;  
@packages = split("\n\n", $a); 
foreach $p (@packages) {
  print "$1: $2\n" if $p =~ /^(.*?):.*?500 http:\/\/ppa\.launchpad\.net\/(.*?)\s/s
}
'

echo "Here is list of packages installed using ppa:"
apt-cache policy $(dpkg --get-selections |
  grep -v deinstall$ |
  awk '{ print $1 }') |
  perl -e "$filter"
