#!/bin/bash

CONFIG="$HOME/Scripts/dmenu/config"
[ -f "$CONFIG" ] && . $CONFIG || DMENU='dmenu -i'

selected="$(ps --user "$(id -u)" -F |
    eval "$DMENU -p 'Search for process to kill:'" |
    awk '{print $2" "$11}')"
if [[ -n $selected ]]; then
    answer="$(echo -e "No\nYes" | dmenu -i -p "Kill $selected?")"
    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<<$selected)"
        kill -9 "$selpid"
        echo "Process $selected has been killed." && exit 1
    fi
    if [[ $answer == "No" ]]; then
        echo "Program terminated." && exit 1
    fi
fi
exit 0