alias mv='mv -i'
alias ..='cd ..'
alias ...='cd ../..'
alias mkdir='mkdir -pv'
alias pip='pip3'
alias l='exa'
alias ll='exa -all'
alias ls='exa -all'
alias xo='xdg-open'
alias pdftk='java -jar $HOME/.local/bin/pdftk-all.jar'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
