#!/usr/bin/env python3
# Swap visible workspace on two monitors, if you have connected them

import i3ipc
import sys

# Create the Connection object that can be used to send commands and subscribe
# to events.
i3 = i3ipc.Connection()

workspaces = i3.get_workspaces()

focused = None
notfocused = None

for workspace in workspaces:
    if workspace.visible and workspace.focused :
        focused = workspace
    elif workspace.visible:
        notfocused = workspace

# checking if any of the workspace is not availiable, in case of single monitor
if notfocused == None or focused == None:
    sys.exit(-1)

command1 = "[workspace=" + notfocused.name + "] " + "move --no-auto-back-and-forth workspace to output " + focused.output
command2 = "[workspace=" + focused.name + "] " + "move --no-auto-back-and-forth workspace to output " + notfocused.output

command1_ret = i3.command(command1)

if not command1_ret[0].success:
    print(command1_ret[0].error)
    sys.exit(-1)

command2_ret = i3.command(command2)

if not command2_ret[0].success:
    print(command1_ret[0].error)
    sys.exit(-2)

command3 = "workspace " + notfocused.name 
command4 = "workspace " + focused.name

command3_ret = i3.command(command3)

if not command3_ret[0].success:
    print(command3_ret[0].error)
    sys.exit(-1)

command4_ret = i3.command(command4)

if not command4_ret[0].success:
    print(command4_ret[0].error)
    sys.exit(-1)