#!/usr/bin/env bash

# @descriotion: check if the solution is valid
# @usage: cpvalidate [soltion] [validator] [generator] [numTest]

for ((testNum = 0; testNum < $4; testNum++)); do
    ./$3 >input
    echo -e "\nTest: $testNum"
    cat input
    ./$1 <input >out
    cat input out >data
    ./$2 <data >res
    result=$(cat res)
    if [ "${result:0:2}" != "OK" ]; then
        echo "Error found!"
        echo "Input:"
        cat input
        echo "Output:"
        cat out
        echo "Validator Result:"
        cat res
        exit
    fi
done
echo Passed $4 tests
