#!/bin/env python3

import sys
import subprocess
import urllib.parse

def translate(FILE, TEXT):
    link = "http://translate.google.com/translate_tts?" + \
        "ie=UTF-8" + "&total=1" + "&idx=0" + "&client=tw-ob" + \
        "&q=" + urllib.parse.quote(TEXT) + \
        "&tl=En-us"
    print(link)
    subprocess.call(['wget', '-q', '-U', 'mozilla',
                '-O', FILE + '.mp3', link])

if __name__ == "__main__":
    if len(sys.argv) != 1:
        FILE = sys.argv[1]
        TEXT = ' '.join(sys.argv[2:])
        translate(FILE, TEXT)
    else:
        try:
            while True:
                file = '/tmp/gspeak'
                text = input('> ')
                translate(file, text)
                subprocess.Popen(['mpv', file + '.mp3'])
        except KeyboardInterrupt:
            exit(0)