#!/bin/bash

idletime=$((1000 * 60 * 60 * 2)) # 2 hours in milliseconds
# idletime=$((1000 * 60 * 1))       # 5 min in milliseconds

while true; do
    idle=$(xprintidle)
    echo $idle
    if (($idle > $idletime)); then
        #sudo shutdown -P now
        notify-send "Shutdown in a minute"
        sleep 60
        dbus-send --system --print-reply \
            --dest=org.freedesktop.login1 \
            /org/freedesktop/login1 \
            "org.freedesktop.login1.Manager.PowerOff" \
            boolean:true
        # in case above fails
        shutdown now
    fi
    sleep 1
done
