#!/bin/bash
# @description: remove the currently playing song in vlc

playerctl metadata xesam:url | python3 -c "import urllib.parse, sys; print('\"' + urllib.parse.unquote(sys.stdin.read())[7:-1] + '\"')" | xargs -I{} rm {}
