#! /bin/sh

lxqt-policykit-agent &
nm-applet &
copyq &
xfce4-power-manager &
libinput-gestures-setup start &
pgrep -x sxhkd > /dev/null && sxhkd -c $HOME/.config/bspwm/sxhkdrc &
picom -b &
dunst &
$HOME/Scripts/wallpaper.sh
$HOME/.config/polybar/launch.sh
# alacritty &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating